config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"
  resources :tasks

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  validates :content, presence: true, length: {maximum: 255}
  validates :status, presence: true, length: {maximum: 10}

end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase!}
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, length: {maximum: 255}, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: {case_sensitive: false}

  has_secure_password

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      flash[:danger] = '権限がありません'
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email]
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end

  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to login_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:show,:edit,:update,:destroy]

  def index
    @tasks = current_user.tasks.order(created_at: :desc)
  end


  def show
  end


  def new
    @task = Task.new
  end


  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      flash[:success] = "タスクを作成しました"
      redirect_to tasks_url
      # tasks_url
    else
      flash.now[:danger] = "作成に失敗しました"
      render :new
    end
  end


  def edit
  end


  def update
    if @task.update(task_params)
      flash[:success] = "タスクを更新しました"
      redirect_to @task
    else
      flash.now[:danger] = "タスクを更新できませんでした"
      render :edit
    end
  end


  def destroy
    @task.destroy

    flash[:success] = "削除されました"
    redirect_to tasks_url
  end



  private

  def task_params
    params.require(:task).permit(:content, :status)
  end


  def correct_user
    @task = current_user.tasks.find_by(id: params[:id])
    unless @task
      flash[:danger] = '権限がありません'
      redirect_to root_url
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'ユーザーを登録しました。'
      redirect_to root_url

    else
      flash.now[:danger] = 'ユーザの登録に失敗しました'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash_message.html.erb
<% flash.each do |key, value|%>
  <div><%= value %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tasklist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/flash_message"%>
    <% if logged_in? %>
      <p>ログイン名：<%= @current_user.name%></p>
      <%= link_to 'ログアウトする', logout_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |t|%>
  <% if task.errors.any? %>
    <ul>
      <% task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= t.label :content,"タスク"%>
  <%= t.text_field :content %>
  <%= t.label :status,"ステータス"%>
  <%= t.text_field :status %>
  <%= t.submit "作成" %>
<% end %>

app/views/tasks/edit.html.erb
<h1>タスク編集ページ</h1>

<%= render "form", task: @task %>

<%= link_to "タスク一覧へ", tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<ul>
  <% @tasks.each do |task|%>
  <li><%=link_to "タスク：#{task.content}ステータス：#{task.status}", task %></li>
  <% end %>
</ul>
<%= link_to "新規タスク作成", new_task_path %>

app/views/tasks/new.html.erb
<h1>新規タスク作成ページ</h1>

<%= render "form",task: @task %>

<%= link_to "タスク一覧へ", tasks_path %>

app/views/tasks/show.html.erb
<h1>タスク詳細ページ</h1>

<p>タスク：<%= @task.content%>　ステータス：<%= @task.status%></p>

<%= link_to "編集", edit_task_path(@task) %>
<%= link_to "削除", @task, method: :delete, data: { confirm: "本当に削除してよろしいですか？"}%>

<%= link_to "一覧へ", tasks_path %>

app/views/users/new.html.erb
<h1>新規登録</h1>
<%= form_with(model: @user, local: true) do |f| %>
  <% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <div>
    <%= f.label :name,'Name' %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :email,'Email' %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password,'Password' %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation,'Confirmation' %>
    <%= f.password_field :password_confirmation %>

  </div>


  <div>
    <%= f.submit 'Sign up'%>
  </div>


<% end %>

<p>User? <%= link_to 'Log in!', login_path %></p>